### ISSUE TITLE
Setting NBT on item fails to copy NBTTagList correctly

### ISSUE THREAD

**Issue by stefvanschie** [I-Al-Istannen/MiniNBT#1]
I'm using this library on Minecraft 1.14.4 in order to add NBT to an item. However, it has been [noted](https://github.com/stefvanschie/IF/issues/33) that when an item previously had lore attached to it, this lore is gone when re-setting the NBT on the item, even when the lore has not been altered or removed.

After some debugging it seems like this library is looking for the `NBTTagList#add(NBTBase)` method. However, this method no longer exists. The method closest to this one is `NBTTagList#add(int, NBTBase)`. I believe, since this method lookup fails, the `NBTWrappers.NBTTagList` stays empty, even though the original list was not empty. Since lore is stored in such a list, this would explain why the lore is suddenly removed when re-setting the NBT tag on the item.

I recognize that the last commit on this repository was quite some time ago, however I figured I might as well give this a shot. Even if you no longer want to fix issues for this project yourself, I'm willing to make a pull request if you do still accept those, just let me know if this is the case.

**Comment by I-Al-Istannen** [comment]
Please state if the issue was, in fact, not properly fixed :)

I will need to give MiniNBT some love, the code looks kinda horrendous... But it is exam season right now, so my time is heavily limited. I will see what I can do after Friday, but this should fix the issue until then.

PRs are welcome :) I will need to reformat the code base to some proper formatter, then contributing should be a bit easier as well. And redesign the Reflection utils, maybe. I will see in a week or so :)

Have a nice day,
I Al Istannen

**Comment by stefvanschie** [comment]
Thank you for your quick response. This seems to have fixed the issue, thank you.

**Comment by I-Al-Istannen** [comment]
No worries! I was quite surprised this is still used :)

I found some time while procrastinating maths and rewrote the reflection backend and fixed some version incompatibilities for TileEntityNBT (which you are probably not using because you sounded sane :D).

It is on the master branch now and should hopefully not break API/ABI compatibility except for what I outlined on the release page or readme.
